var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_global-error/page.js")
R.c("server/chunks/ssr/_12obk0o._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0kw8d_k._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0gl78zj.js")
R.c("server/chunks/ssr/node_modules_next_dist_0_cm3~p._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0_d82l6._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0tz4w46._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/apps_web__next-internal_server_app__global-error_page_actions_0.u5cfa.js")
R.m(47714)
module.exports=R.m(47714).exports
