var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/sign-up/[[...sign-up]]/page.js")
R.c("server/chunks/ssr/node_modules_0rgw8_w._.js")
R.c("server/chunks/ssr/[root-of-the-server]__08ojs_c._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_00xse_0._.js")
R.c("server/chunks/ssr/node_modules_next_dist_compiled_07ho8ku._.js")
R.c("server/chunks/ssr/node_modules_next_dist_server_route-modules_app-page_0f6k0sl._.js")
R.c("server/chunks/ssr/[externals]__0n13xf4._.js")
R.c("server/chunks/ssr/[externals]_next_dist_compiled_@vercel_og_index_node_0zh~5pq.js")
R.c("server/chunks/ssr/node_modules_0c5-q2w._.js")
R.c("server/chunks/ssr/apps_web_src_app_0l44dwz._.js")
R.c("server/chunks/ssr/apps_web_src_0g10b15._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/node_modules_@clerk_nextjs_dist_esm_server_0mz33il._.js")
R.c("server/chunks/ssr/_0aev501._.js")
R.c("server/chunks/ssr/[externals]_node_crypto_0xdk2m3._.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-page.js?page=/sign-up/[[...sign-up]]/page { METADATA_0 => \"[project]/apps/web/src/app/favicon.ico.mjs { IMAGE => \\\"[project]/apps/web/src/app/favicon.ico (static in ecmascript, tag client)\\\" } [app-rsc] (structured image object, ecmascript)\", METADATA_1 => \"[project]/apps/web/src/app/icon--metadata.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_2 => \"[project]/apps/web/src/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_3 => \"[project]/node_modules/next/dist/client/components/builtin/not-found.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_4 => \"[project]/node_modules/next/dist/client/components/builtin/forbidden.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_5 => \"[project]/node_modules/next/dist/client/components/builtin/unauthorized.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_6 => \"[project]/node_modules/next/dist/client/components/builtin/global-error.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_7 => \"[project]/apps/web/src/app/sign-up/[[...sign-up]]/page.tsx [app-rsc] (ecmascript, Next.js Server Component)\" } [app-rsc] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-page.js?page=/sign-up/[[...sign-up]]/page { METADATA_0 => \"[project]/apps/web/src/app/favicon.ico.mjs { IMAGE => \\\"[project]/apps/web/src/app/favicon.ico (static in ecmascript, tag client)\\\" } [app-rsc] (structured image object, ecmascript)\", METADATA_1 => \"[project]/apps/web/src/app/icon--metadata.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_2 => \"[project]/apps/web/src/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_3 => \"[project]/node_modules/next/dist/client/components/builtin/not-found.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_4 => \"[project]/node_modules/next/dist/client/components/builtin/forbidden.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_5 => \"[project]/node_modules/next/dist/client/components/builtin/unauthorized.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_6 => \"[project]/node_modules/next/dist/client/components/builtin/global-error.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_7 => \"[project]/apps/web/src/app/sign-up/[[...sign-up]]/page.tsx [app-rsc] (ecmascript, Next.js Server Component)\" } [app-rsc] (ecmascript)").exports
